### ISSUE TITLE
Addin instalation Xamarin studio 6

### ISSUE THREAD

**Issue by jzeferino** [CalebMorris/Xamarin-ResxEditor#21]
When following the readme instructions i changed to _Alpha Channel_  option in the Add-in manager and searched for Resx. 

Nothing came up.

Xamarin studio 6.0.1 Build 9

**Comment by CalebMorris** [comment]
Xamarin completely changed the way that addins work with 6.\* and have a different available store to select from.
I haven't had the free time recently to update this addin so it will currently only work for 5, sorry.
I'll try to work on updating it soon.

**Comment by jzeferino** [comment]
Thank you.
Update me when you have time to do it.

**Comment by alextn** [comment]
Hi @CalebMorris have you any idea about a release date ?

**Comment by CalebMorris** [comment]
Hi @alextn .
I started a new job about 6 months ago and haven't work on any C# since then due to how busy I have been and no longer using it at work.
Im planning to add a badge to show this project is unmaintained until I get get a more regular schedule.
If anyone wants write permissions or add-in permissions to update it I'm fine handing it over, but otherwise I don't see me getting time until at least next year.
